# Generated by Django 5.2.1 on 2025-05-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_vendorprofile_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
